# Generated automatically from Makefile.in by configure.

# Set WIN32 on the line below to 'TRUE' if building on Windows, otherwise
# set it to 'FALSE'
export WIN32=TRUE
  
# List of all modules to compile
# You can remove "dom" if you don't intend to use the DOM interface
MODULES=unicode input_sources sax dom

##############################
##  Main Makefile: three targets are available:
##    obj:   build all objects (no executable)
##    test:  build the test programs found in the modules
##    clean: remove all object files and temporary files
##    install: install all the files under the PREFIX hierarchy, as
##           defined in Makefile.module
##############################

MODULE_OBJ=${MODULES:%=-aO%/obj}
MODULE_SRC=${MODULES:%=-aI%}
MODULE_CLEAN=${MODULES:%=%_clean}
MODULE_TEST=${MODULES:%=%_test}
MODULE_INSTALL=${MODULES:%=%_install}

RANLIB= ranlib
CHMOD=chmod
ARFLAGS=cr
CP=cp -p -f
MKDIR=mkdir -p

.PHONY: all obj test clean install

all: obj test docs
obj: ${MODULES}

docs: force
	${MAKE} -e -C docs

${MODULES}: force
	${MAKE} -e -C $@ all_obj

${MODULE_CLEAN}: force
	${MAKE} -e -C ${@:%_clean=%} clean

${MODULE_TEST}: force
	${MAKE} -e -C ${@:%_test=%} test

${MODULE_INSTALL}: force
	${MAKE} -e -C ${@:%_install=%} install

install: ${MODULE_INSTALL}
	@echo "Installation finished"

test: force
	${MAKE} -e ${MODULE_TEST}

clean: force
	-${RM} *.o
	-${RM} *.ali
	-${RM} textxml
	-${RM} b~*
	${MAKE} -e ${MODULE_CLEAN}
	cd docs; ${MAKE} -e clean

force:
