#!/bin/sh

## Location of the testsuite's files for Schemas
## You can download these from
##   http://www.w3.org/XML/2001/05/xmlschema-test-collection

xmltests=./xmltests

debug=""

while getopts "d" opt
do 
   case $opt in
      d) debug="-debug";;
      *) echo "Invalid command line switch: $opt"
         exit 1
         ;;
   esac
done


XML="./testschema $debug"
ms=$xmltests/msxsdtest

total=0
failed=0
passed=0
not_run=0

#######################################
## summary ()
#######################################

summary() {
  echo "Total: $total  Passed: $passed   Failed: $failed  Notrun: $not_run"
}

#######################################
## expect()
##   $1=schema file (can be empty)
##   $2=test file (can be empty)
##   $3=expected output
#######################################

expect() {
   xsd_file="$1"
   xml_file="$2"
   expected="$3"

   xsd=""
   if [ x"$xsd_file" != x ]; then
     xsd="-xsd $xsd_file"
   fi

   out=`eval $XML $xsd $xml_file 2>&1`
   total=`expr $total + 1`

   if [ x"$out" != x"$expected" ]; then
      quoted=`echo $out | sed -e 's/\"/\\\"/g' -e 's,'$ms',\$ms,'`
      echo "#------------ Test failed ------------"
      echo "  cmd: $XML $xsd $xml_file"
      #echo "   output= $out"
      echo "  quoted= $quoted"
      echo "  expected= $expected"
      failed=`expr $failed + 1`
   else
      passed=`expr $passed + 1`
   fi
}

##################
## not_run()
##  $1=testname
##  $2=why
##################

notrun() {
  not_run=`expr $not_run + 1`
}

##################
## Microsoft elements tests -- A serie  (name attribute tests)
##################

expect $ms/element/elemA001.xsd ""\
 "$ms/element/elemA001.xsd:3:16: Attribute \"name\" is required in this context"
expect $ms/element/elemA002.xsd "" ""
expect $ms/element/elemA003.xsd "" ""
expect $ms/element/elemA004.xsd "" ""
expect $ms/element/elemA005.xsd "" ""
expect $ms/element/elemA006.xsd "" \
 "$ms/element/elemA006.xsd:4:27: Element \"foo\" has already been declared"
expect $ms/element/elemA007.xsd "" ""
expect $ms/element/elemA009.xsd "" \
 "$ms/element/elemA009.xsd:3:31: Attribute \"name\": Invalid value: \"foo:bar\""
expect $ms/element/elemA010.xsd "" \
 "$ms/element/elemA010.xsd:3:28: Attribute \"name\": Invalid value: \":bar\""
expect $ms/element/elemA011.xsd "" \
 "$ms/element/elemA011.xsd:3:28: Attribute \"name\": Invalid value: \"foo:\""
expect $ms/element/elemA012.xsd "" \
 "$ms/element/elemA012.xsd:3:24: Attribute \"name\": Invalid value: \"\""
expect $ms/element/elemA013.xsd "" \
 "$ms/element/elemA013.xsd:3:25: Attribute \"name\": Invalid value: \"\""
expect $ms/element/elemA014.xsd "" \
 "$ms/element/elemA014.xsd:3:31: Attribute \"name\": Invalid value: \"-2.5foo\""
expect $ms/element/elemA015.xsd "" ""
expect $ms/element/elemA016.xsd "" ""
expect $ms/element/elemA017.xsd "" ""


##################
## Microsoft elements tests -- B serie  (boolean tests)
##################

expect $ms/element/elemB001.xsd "" ""
expect $ms/element/elemB002.xsd "" ""
expect $ms/element/elemB003.xsd "" \
 "$ms/element/elemB003.xsd:3:49: Attribute \"abstract\": Invalid value for boolean type: \"false true\""
expect $ms/element/elemB004.xsd "" \
 "$ms/element/elemB004.xsd:3:44: Attribute \"abstract\": Invalid value for boolean type: \"False\""
expect $ms/element/elemB005.xsd "" \
 "$ms/element/elemB005.xsd:3:39: Attribute \"abstract\": Invalid value for boolean type: \"\""
expect $ms/element/elemB006.xsd "" \
 "$ms/element/elemB006.xsd:3:46: Attribute \"abstract\": Invalid value for boolean type: \"boolean\""
expect $ms/element/elemB007.xsd "" ""
expect $ms/element/elemB008.xsd "" ""
expect $ms/element/elemB009.xsd "" \
 "$ms/element/elemB009.xsd:3:47: Attribute \"abstract\": Invalid value for boolean type: \"abstract\""
expect $ms/element/elemB010.xsd "" \
 "$ms/element/elemB010.xsd:3:49: Attribute \"abstract\": Invalid value for boolean type: \"true false\""


##################
## Microsoft elements tests -- C serie  (block attribute + list type)
##################

expect $ms/element/elemC001.xsd "" ""
expect $ms/element/elemC002.xsd "" ""
expect $ms/element/elemC003.xsd "" ""
expect $ms/element/elemC004.xsd "" ""
expect $ms/element/elemC005.xsd "" ""
expect $ms/element/elemC006.xsd "" ""
expect $ms/element/elemC007.xsd "" ""
expect $ms/element/elemC008.xsd "" ""
expect $ms/element/elemC009.xsd "" \
 "$ms/element/elemC009.xsd:3:39: Attribute \"block\": Invalid value \"foo\""
expect $ms/element/elemC010.xsd "" \
 "$ms/element/elemC010.xsd:3:40: Attribute \"block\": Invalid value \"#All\""
expect $ms/element/elemC011.xsd "" \
 "$ms/element/elemC011.xsd:3:45: Attribute \"block\": Invalid value \"Extension\""
expect $ms/element/elemC012.xsd "" \
 "$ms/element/elemC012.xsd:3:47: Attribute \"block\": Invalid value \"Restriction\""
expect $ms/element/elemC013.xsd "" \
 "$ms/element/elemC013.xsd:3:48: Attribute \"block\": Invalid value \"Substitution\""
expect $ms/element/elemC014.xsd "" \
 "$ms/element/elemC014.xsd:3:75: Attribute \"block\": Invalid value \"#all extension restriction substitution\""
expect $ms/element/elemC015.xsd "" \
 "$ms/element/elemC015.xsd:3:49: Attribute \"block\": Invalid value \"extension foo\""
expect $ms/element/elemC016.xsd "" \
 "$ms/element/elemC016.xsd:3:51: Attribute \"block\": Invalid value \"restriction foo\""
expect $ms/element/elemC017.xsd "" \
 "$ms/element/elemC017.xsd:3:52: Attribute \"block\": Invalid value \"substitution foo\""
expect $ms/element/elemC018.xsd "" ""
expect $ms/element/elemC020.xsd "" ""

##################
## Microsoft elements tests -- D serie (default)
##################

expect $ms/element/elemD001.xsd "" ""
expect $ms/element/elemD002.xsd "" ""
expect $ms/element/elemD003.xsd "" \
 "$ms/element/elemD003.xsd:3:72: Attributes \"fixed\" and \"default\" conflict with each other"
expect $ms/element/elemD004.xsd "" \
 "$ms/element/elemD004.xsd:9:56: No character data allowed by content model"
expect $ms/element/elemD005.xsd "" \
 "$ms/element/elemD005.xsd:3:58: string pattern not matched: \d\d\d\d-\d\d-\d\d"
expect $ms/element/elemD006.xsd "" ""

##################
## Microsoft elements tests -- E serie
##################

expect $ms/element/elemE001.xsd "" ""
expect $ms/element/elemE002.xsd "" ""
expect $ms/element/elemE003.xsd "" ""
expect $ms/element/elemE004.xsd "" ""
expect $ms/element/elemE005.xsd "" ""
expect $ms/element/elemE006.xsd "" \
 "$ms/element/elemE006.xsd:3:62: Attribute \"name\": Invalid value: \"-foo\""
expect $ms/element/elemE007.xsd "" \
 "$ms/element/elemE007.xsd:4:50: Attribute \"substitutionGroup\": Invalid value: \"\""
expect $ms/element/elemE008.xsd "" \
 "$ms/element/elemE008.xsd:11: Element \"foo\" was referenced, but never declared"
expect $ms/element/elemE009.xsd "" \
 "$ms/element/elemE009.xsd:16: Element \"foo\" was referenced, but never declared"

##################
## Microsoft elements tests -- F serie (final)
##################

expect $ms/element/elemF001.xsd "" ""
expect $ms/element/elemF002.xsd "" ""
expect $ms/element/elemF003.xsd "" ""
expect $ms/element/elemF004.xsd "" \
 "$ms/element/elemF004.xsd:3:48: Attribute \"final\": Invalid value \"substitution\""
expect $ms/element/elemF005.xsd "" ""
expect $ms/element/elemF006.xsd "" \
 "$ms/element/elemF006.xsd:3:60: Attribute \"final\": Invalid value \"restriction substitution\""
expect $ms/element/elemF007.xsd "" \
 "$ms/element/elemF007.xsd:3:58: Attribute \"final\": Invalid value \"substitution extension\""
expect $ms/element/elemF008.xsd "" \
 "$ms/element/elemF008.xsd:3:70: Attribute \"final\": Invalid value \"extension restriction substitution\""
expect $ms/element/elemF009.xsd "" \
 "$ms/element/elemF009.xsd:3:39: Attribute \"final\": Invalid value \"foo\""
expect $ms/element/elemF010.xsd "" \
 "$ms/element/elemF010.xsd:3:40: Attribute \"final\": Invalid value \"#All\""
expect $ms/element/elemF011.xsd "" \
 "$ms/element/elemF011.xsd:3:45: Attribute \"final\": Invalid value \"Extension\""
expect $ms/element/elemF012.xsd "" \
 "$ms/element/elemF012.xsd:3:47: Attribute \"final\": Invalid value \"Restriction\""
expect $ms/element/elemF013.xsd "" \
 "$ms/element/elemF013.xsd:3:48: Attribute \"final\": Invalid value \"Substitution\""
expect $ms/element/elemF014.xsd "" \
 "$ms/element/elemF014.xsd:3:75: Attribute \"final\": Invalid value \"#all extension restriction substitution\""
expect $ms/element/elemF015.xsd "" \
 "$ms/element/elemF015.xsd:3:49: Attribute \"final\": Invalid value \"extension foo\""
expect $ms/element/elemF016.xsd "" \
 "$ms/element/elemF016.xsd:3:51: Attribute \"final\": Invalid value \"restriction foo\""
expect $ms/element/elemF017.xsd "" \
 "$ms/element/elemF017.xsd:3:52: Attribute \"final\": Invalid value \"substitution foo\""
expect $ms/element/elemF018.xsd "" ""


##################
## Microsoft elements tests -- G serie
##################

expect $ms/element/elemG001.xsd "" ""
expect $ms/element/elemG002.xsd "" ""
expect $ms/element/elemG003.xsd "" \
 "$ms/element/elemG003.xsd:8:21: No character data allowed by content model"
expect $ms/element/elemG004.xsd "" \
 "$ms/element/elemG004.xsd:8:21: No character data allowed by content model"
expect $ms/element/elemG005.xsd "" ""


##################
## Microsoft elements tests -- H serie
##################

expect $ms/element/elemH001.xsd "" ""
expect $ms/element/elemH002.xsd "" ""
expect $ms/element/elemH003.xsd "" \
 "$ms/element/elemH003.xsd:2:80: Attribute \"elementFormDefault\": Element's value not in the enumeration set"
expect $ms/element/elemH004.xsd "" \
 "$ms/element/elemH004.xsd:2:89: Attribute \"elementFormDefault\": Element's value not in the enumeration set"
expect $ms/element/elemH005.xsd "" \
 "$ms/element/elemH005.xsd:2:91: Attribute \"elementFormDefault\": Element's value not in the enumeration set"
expect $ms/element/elemH006.xsd "" \
 "$ms/element/elemH006.xsd:2:101: Attribute \"elementFormDefault\": Element's value not in the enumeration set"

##################
## Microsoft elements tests -- I serie
##################

expect $ms/element/elemI001.xsd "" ""
expect $ms/element/elemI002.xsd "" ""
expect $ms/element/elemI003.xsd "" \
 "$ms/element/elemI003.xsd:3:35: Attribute \"id\": Invalid value: \"25\""
expect $ms/element/elemI004.xsd "" \
 "$ms/element/elemI004.xsd:3:33: Attribute \"id\": Invalid value: \"\""
expect $ms/element/elemI005.xsd "" \
 "$ms/element/elemI005.xsd:4:39: ID \"foo25\" already defined"

##################
## Microsoft elements tests -- J serie
##################

expect $ms/element/elemJ001.xsd "" ""
expect $ms/element/elemJ002.xsd "" ""
expect $ms/element/elemJ003.xsd "" ""
expect $ms/element/elemJ004.xsd "" ""
expect $ms/element/elemJ005.xsd "" ""
expect $ms/element/elemJ006.xsd "" \
 "$ms/element/elemJ006.xsd:6:43: Attribute \"maxOccurs\": Invalid value \"\""
expect $ms/element/elemJ007.xsd "" \
 "$ms/element/elemJ007.xsd:6:45: Attribute \"maxOccurs\": Invalid value \"-1\""
expect $ms/element/elemJ008.xsd "" \
 "$ms/element/elemJ008.xsd:6:52: Attribute \"maxOccurs\": Invalid value \"Unbounded\""
expect $ms/element/elemJ009.xsd "" ""
expect $ms/element/elemJ010.xsd "" ""
expect $ms/element/elemJ011.xsd "" ""
expect $ms/element/elemJ012.xsd "" \
 "$ms/element/elemJ012.xsd:6:52: Attribute \"minOccurs\": Value must be an integer"
expect $ms/element/elemJ013.xsd "" ""
expect $ms/element/elemJ014.xsd "" \
 "$ms/element/elemJ014.xsd:6:43: Attribute \"minOccurs\": Value must be an integer"
expect $ms/element/elemJ015.xsd "" \
 "$ms/element/elemJ015.xsd:6:45: Attribute \"minOccurs\": minInclusive is set to 0"
expect $ms/element/elemJ016.xsd "" \
 "$ms/element/elemJ016.xsd:6:52: Attribute \"minOccurs\": Value must be an integer"
expect $ms/element/elemJ017.xsd "" ""
expect $ms/element/elemJ018.xsd "" ""
expect $ms/element/elemJ019.xsd "" \
 "$ms/element/elemJ019.xsd:6:58: minOccurs > maxOccurs when creating particle"
expect $ms/element/elemJ020.xsd "" \
 "$ms/element/elemJ020.xsd:6:74: Attribute \"minOccurs\": Value must be an integer"
expect $ms/element/elemJ021.xsd "" ""

##################
## Microsoft elements tests -- K serie
##################

expect $ms/element/elemK001.xsd "" ""
expect $ms/element/elemK002.xsd "" ""
expect $ms/element/elemK003.xsd "" \
 "$ms/element/elemK003.xsd:3:39: Attribute \"nillable\": Invalid value for boolean type: \"\""
expect $ms/element/elemK004.xsd "" \
 "$ms/element/elemK004.xsd:3:43: Attribute \"nillable\": Invalid value for boolean type: \"True\""
expect $ms/element/elemK005.xsd "" \
 "$ms/element/elemK005.xsd:3:44: Attribute \"nillable\": Invalid value for boolean type: \"False\""
expect $ms/element/elemK006.xsd "" \
 "$ms/element/elemK006.xsd:3:49: Attribute \"nillable\": Invalid value for boolean type: \"true false\""
expect $ms/element/elemK007.xsd "" \
 "$ms/element/elemK007.xsd:3:43: Attribute \"nullable\": Invalid in this context"

##################
## Microsoft elements tests -- L serie
##################

expect $ms/element/elemL001.xsd "" ""
expect $ms/element/elemL002.xsd "" \
 "$ms/element/elemL002.xsd:10: Element \"foo\" was referenced, but never declared"
expect $ms/element/elemL003.xsd "" \
 "$ms/element/elemL003.xsd:5:39: \"ref\" attribute cannot be self-referencing"
expect $ms/element/elemL004.xsd "" ""
expect $ms/element/elemL005.xsd "" \
 "$ms/element/elemL005.xsd:3:14: Not enough occurrences of sequence, expecting at least 1, got 0"

##################
## Microsoft elements tests -- M serie
##################

expect $ms/element/elemM001.xsd "" ""
expect $ms/element/elemM002.xsd "" \
 "$ms/element/elemM002.xsd:6: Type \"foo\" was referenced, but never declared"
expect $ms/element/elemM003.xsd "" \
 "$ms/element/elemM003.xsd:5:31: Self-referencing restriction not allowed"
expect $ms/element/elemM004.xsd "" ""
expect $ms/element/elemM005.xsd "" \
 "$ms/element/elemM005.xsd:6:39: \"type\" attribute cannot be specified along with \"ref\""

##################
## Microsoft elements tests -- N serie
##################

expect $ms/element/elemN001.xsd "" ""
expect $ms/element/elemN002.xsd "" ""
expect $ms/element/elemN003.xsd "" ""
expect $ms/element/elemN004.xsd "" ""
expect $ms/element/elemN005.xsd "" ""
expect $ms/element/elemN006.xsd "" \
 "$ms/element/elemN006.xsd:3:58: Attribute \"foo\": Invalid in this context"

##################
## Microsoft elements tests -- O serie
##################

expect "" $ms/element/elemO001.xml \
 "$ms/element/elemO001.xml:4:11: \"parent\" is an abstract element"
expect "" $ms/element/elemO002.xml ""
expect "" $ms/element/elemO003.xml ""
expect "" $ms/element/elemO004.xml ""
expect "" $ms/element/elemO005.xml ""
expect "" $ms/element/elemO006.xml ""
expect "" $ms/element/elemO007.xml \
 "$ms/element/elemO007.xml:3:33: Element has character data, but is declared as nil"
expect "" $ms/element/elemO008.xml ""
expect "" $ms/element/elemO009.xml ""
expect "" $ms/element/elemO010.xml \
 "$ms/element/elemO010.xml:3:27: Attribute \"xsi:nil\" invalid for this element"
expect "" $ms/element/elemO011.xml \
 "$ms/element/elemO011.xml:3:27: Attribute \"xsi:nil\" invalid for this element"
expect "" $ms/element/elemO012.xml ""

##################
## Microsoft elements tests -- P serie
##################

expect $ms/element/elemP001.xsd "" \
 "$ms/element/elemP001.xsd:3:90: Attributes \"fixed\" and \"default\" conflict with each other"
expect $ms/element/elemP002.xsd "" \
 "$ms/element/elemP002.xsd:5:92: Attributes \"fixed\" and \"default\" conflict with each other"
expect $ms/element/elemP003.xsd "" ""
expect $ms/element/elemP004.xsd "" ""
expect $ms/element/elemP005.xsd "" \
 "$ms/element/elemP005.xsd:5:18: Either \"name\" or \"ref\" attribute must be present"
expect $ms/element/elemP006.xsd "" \
 "$ms/element/elemP006.xsd:6:45: \"ref\" attribute cannot be self-referencing"
expect $ms/element/elemP007.xsd "" \
 "$ms/element/elemP007.xsd:11:23: Cannot mix complexType definition and \"ref\" attribute"
expect $ms/element/elemP008.xsd "" \
 "$ms/element/elemP008.xsd:9:22: Cannot mix complexType definition and \"ref\" attribute"
expect $ms/element/elemP009.xsd "" \
 "$ms/element/elemP009.xsd:6:49: \"type\" attribute cannot be specified along with \"ref\""

##################
## Microsoft elements tests -- Q serie
##################

expect $ms/element/elemQ001.xsd "" ""
expect $ms/element/elemQ002.xsd "" ""
expect $ms/element/elemQ003.xsd "" ""
expect $ms/element/elemQ004.xsd "" \
 "$ms/element/elemQ004.xsd:7:19: Too many occurrences of sequence. Expecting at most 1"
expect $ms/element/elemQ005.xsd "" ""
expect $ms/element/elemQ006.xsd "" \
 "$ms/element/elemQ006.xsd:10:19: Too many occurrences of sequence. Expecting at most 1"
expect "" $ms/element/elemQ007.xml \
 "$ms/element/elemQ007.xml:3:8: Not enough occurrences of sequence, expecting at least 1, got 0"
expect "" $ms/element/elemQ008.xml ""
expect "" $ms/element/elemQ009.xml \
 "$ms/element/elemQ009.xml:4:11: Element \"fooTest\" is repeated too many times, maximum number of occurrences is 1"
expect "" $ms/element/elemQ010.xml \
 "$ms/element/elemQ010.xml:3:8: Not enough occurrences of sequence, expecting at least 1, got 0"
expect "" $ms/element/elemQ011.xml ""
expect "" $ms/element/elemQ012.xml \
 "$ms/element/elemQ012.xml:4:11: Too many occurrences of sequence. Expecting at most 1"
expect "" $ms/element/elemQ013.xml ""
expect "" $ms/element/elemQ014.xml \
 "$ms/element/elemQ014.xml:5:11: Too many occurrences of sequence. Expecting at most 1"
expect "" $ms/element/elemQ015.xml ""
expect $ms/element/elemQ016.xsd "" ""
expect "" $ms/element/elemQ017.xml ""
expect "" $ms/element/elemQ018.xml \
 "$ms/element/elemQ018.xml:3:23: Element's value must be \"Hello\""
expect "" $ms/element/elemQ019.xml \
 "$ms/element/elemQ019.xml:3:21: Element's value must be \"Hello\""
expect "" $ms/element/elemQ020.xml ""
expect "" $ms/element/elemQ021.xml ""
expect "" $ms/element/elemQ022.xml ""

##################
## Microsoft elements tests -- R serie
##################

expect "" $ms/element/elemR001.xml ""
expect "" $ms/element/elemR002.xml ""
notrun $ms/element/elemR003.xsd "test seems wrong, all parsers fail"
expect "" $ms/element/elemR004.xml ""
expect "" $ms/element/elemR005.xml ""
notrun $ms/element/elemR006.xsd "test seems wrong, all parsers fail"















summary
