#!/bin/sh

PATH=`pwd`/..:$PATH
export PATH


testsax_internal() {
   cmd=$1
   dir=$2
   xml=$3
   out=$4
   
   (
   cd $dir
   eval $cmd $xml > tmp 2>&1
   if diff $out tmp >/dev/null 2>&1; then
      true;
   else
      echo "----- $dir $xml ------"
      diff $out tmp
   fi
   rm tmp
   )
}

testsax_silent() {
   testsax_internal "testsax -silent" "$@"
}

testsax_verbose() {
   testsax_internal "testsax" "$@"
} 


testsax_verbose . not_found.xml not_found.xml.out
testsax_silent  external/ SetworksParams.XML test.out

